# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  android: circleci/android@2.2.0

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
    build-workflow:
      jobs:
        - android/build:
            executor: 
              name: android/android-machine
              resource-class: large
              tag: 2021.10.1 

