version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28
    environment:
      TERM: xtermn
    working_directory: ~/repo
    steps:
      # Install Node.js
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
            npm run android:build
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build APK
          command: |
            cd android && ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: app-release-unsigned.apk
      - run:
          name: Sign APK
          command: |
            echo ${ANDROID_KEYSTORE_BASE64} | base64 -d > keystore.jks
            jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks -storepass ${ANDROID_KEYSTORE_PASSWORD} -keypass ${ANDROID_KEY_PASSWORD} app-release-unsigned.apk ${ANDROID_KEY_ALIAS}
      - run:
          name: Zipalign APK
          command: |
            ~/android-sdk/build-tools/30.0.3/zipalign -v 4 app-release-unsigned.apk app-release.apk
      - store_artifacts:
          path: app-release.apk
          destination: app-release-signed.apk
          